steps:
- name: 'gcr.io/cloud-builders/gcloud'
  args:
  - functions
  - deploy
  - pwr_5_teams_API
  - --source=./college_football_teams
  - --entry-point=power5teamsAPI
  - --trigger-http
  - --allow-unauthenticated
  - --runtime=python39
  - --memory=1024MB
  - --timeout=540s